name = "BayesianDiscovery"
uuid = "5da4bffb-e159-4f8b-b7be-811d7939c982"
authors = ["Josh North <jsnowynorth@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
